### ISSUE TITLE
論理設計のアンチパターン

### ISSUE THREAD

**Issue by nakamori-naoya** [nakamori-naoya/engineering-guidelines#16]
# 🤖 生成AIへの重要な指示（YAML最優先で読み込み）

以下のYAMLブロックを最優先で読み込み、Bill Karwinの「SQLアンチパターン」に基づく物理設計ガイドラインとして活用してください。

## 🤖 AI向け構造化データ（YAMLブロック）

```yaml
# 物理設計のアンチパターンガイド（Bill Karwin）
antipatterns:
  physical_design:
    - name: "Multi-Column Attributes"
      description: "繰り返し項目による複数カラム"
      problem:
        - "phone1, phone2, phone3 のような連番カラム"
        - "固定された列数制限"
        - "NULL値の無駄"
        - "クエリの複雑化"
        - "スキーマ変更の必要性"
      bad_example: |
        CREATE TABLE users (
          user_id INT PRIMARY KEY,
          phone1 VARCHAR(20),
          phone2 VARCHAR(20),
          phone3 VARCHAR(20),
          email1 VARCHAR(255),
          email2 VARCHAR(255),
          email3 VARCHAR(255)
        );
      good_example: |
        CREATE TABLE user_phones (
          phone_id INT PRIMARY KEY,
          user_id INT,
          phone_number VARCHAR(20),
          phone_type VARCHAR(20),
          is_primary BOOLEAN,
          FOREIGN KEY (user_id) REFERENCES users(user_id)
        );

    - name: "Metadata Proliferation"
      description: "メタデータ大増殖"
      problem:
        - "日付・地域別テーブル分割"
        - "同一構造テーブルの複製"
        - "メンテナンスの困難"
        - "統計処理の複雑化"
      bad_example: |
        sales_2022_01 (...)
        sales_2022_02 (...)
        customers_tokyo (...)
        customers_osaka (...)
      solutions:
        - "パーティショニング"
        - "単一テーブル + インデックス"
        - "アーカイブ戦略"

design_patterns:
  one_to_many:
    description: "1対多関係での解決"
    example: |
      CREATE TABLE contact_methods (
        contact_id INT PRIMARY KEY,
        user_id INT,
        contact_type ENUM('phone', 'email', 'address'),
        contact_value VARCHAR(255),
        is_primary BOOLEAN,
        FOREIGN KEY (user_id) REFERENCES users(user_id)
      );
  
  partitioning:
    description: "パーティショニングによる解決"
    strategies:
      - "日付範囲パーティション"
      - "ハッシュパーティション"
      - "リストパーティション"
    
  archiving:
    description: "アーカイブ戦略"
    methods:
      - "履歴テーブルの分離"
      - "自動アーカイブプロセス"
      - "圧縮とストレージ最適化"

optimization_principles:
  - "論理的完整性の維持"
  - "物理的最適化の透明性"
  - "メンテナンス自動化の検討"
  - "パフォーマンス測定の実施"

checklist:
  physical_design:
    - "連番カラムの回避"
    - "テーブル構造の重複排除"
    - "カラム数制限の回避"
    - "日付・地域のテーブル名回避"
    - "パーティショニング検討"
    - "アーカイブ戦略検討"
    - "インデックス設計"
    - "ストレージ効率化"
```

---

# 物理設計のアンチパターン

## 概要
この文書では、Bill Karwinの「SQL Antipatterns」に基づく物理設計のアンチパターンについて説明します。効率的で保守しやすいデータベース物理設計の指針を提供します。

#### アンチパターンの兆候
```sql
users (
 user_id INT PRIMARY KEY,
 phone1 VARCHAR(20),
 phone2 VARCHAR(20),
 phone3 VARCHAR(20),
 email1 VARCHAR(255),
 email2 VARCHAR(255),
 email3 VARCHAR(255)
)
```

#### なぜ問題なのか
- 固定されたカラム数制限
- 無駄なNULL値
- 複雑なクエリ
- 新しい項目のためのスキーマ変更が必要

#### 解決パターン
1. 1対多関係
```sql
-- 電話番号とメールを別テーブルに分離
user_phones (
 phone_id INT PRIMARY KEY,
 user_id INT,
 phone_number VARCHAR(20),
 phone_type VARCHAR(20),
 is_primary BOOLEAN
)

user_emails (
 email_id INT PRIMARY KEY,
 user_id INT,
 email VARCHAR(255),
 email_type VARCHAR(20),
 is_primary BOOLEAN
)
```

#### アンチパターンの兆候
```sql
-- 日付や地域別の複数テーブル
sales_2022_01 (...)
sales_2022_02 (...)
customers_tokyo (...)
customers_osaka (...)
```

#### 解決パターン
1. パーティショニングを使用した単一テーブル
2. インデックスを使用した単一テーブル
3. アーカイブ戦略

## 主要な設計原則
- 論理的完全性を維持
- 物理的最適化を透明にする
- メンテナンス自動化を検討

## 物理設計のチェックリスト
- [ ] 連番カラムを避ける
- [ ] テーブル構造を重複させない
- [ ] カラム数を制限しない
- [ ] テーブル名に日付/地域を避ける
- [ ] パーティショニングを検討
- [ ] アーカイブ戦略を検討

## 実践例：連絡先管理
```sql
CREATE TABLE contact_methods (
 contact_id INT PRIMARY KEY,
 user_id INT,
 contact_type ENUM('phone', 'email', 'address'),
 contact_value VARCHAR(255),
 priority INT,
 is_active BOOLEAN,
 created_at TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(user_id)
);
```

## パフォーマンスの考慮事項
- 大規模テーブルのインデックス戦略
- 時系列データのパーティショニング
- 履歴データのアーカイブポリシー
- ストレージ最適化技術
