### ISSUE TITLE
業務知識YAML構造化プロンプト

### ISSUE THREAD

**Issue by nakamori-naoya** [nakamori-naoya/engineering-guidelines#20]
# 業務知識YAML構造化プロンプト

生成AIが業務知識を構造化して理解するためのプロンプトテンプレート。

## 概要

このプロンプトは、業務知識を生成AIが理解しやすいYAML形式で構造化するためのガイドラインです。増田亨氏のドメイン駆動設計の考え方を参考に、業務上の制約、不変条件、ルール、状態変化を中心に整理します。

## 主な特徴

- **業務言語の重視**: 実装用語ではなく、業務で実際に使われる言葉を使用
- **制約条件の明確化**: 不変条件、ビジネスルール、制約を具体的に記述
- **状態遷移の可視化**: ライフサイクルにおけるイベントと状態変化を明示
- **理由の説明**: なぜそのルールが存在するかの業務的な理由を含める

## 構造化される要素

1. **コアドメインの識別**
   - 競争優位性
   - 独自の価値
   - 複雑さの理由

2. **業務概念と制約**
   - 不変条件（invariants）
   - 制約条件（constraints）
   - ライフサイクル（状態遷移）

3. **ビジネスルール**
   - 検証・計算・判定・制限のルール
   - 適用条件
   - 例外処理

4. **業務イベント**
   - トリガー
   - 事前条件・事後条件
   - 業務への影響

5. **業務フロー**
   - ステップごとの実行条件
   - アクター
   - 検証事項

6. **用語定義（ユビキタス言語）**
   - 業務での使われ方
   - 関連するルール

## 使用方法

1. このプロンプトを生成AIに提示
2. 業務知識をテキストで入力
3. YAML形式で構造化された出力を取得

## 関連情報

- 増田亨『現場で役立つシステム設計の原則』
- Eric Evans『Domain-Driven Design』

## ファイル

[business-knowledge-yaml-prompt.md](business-knowledge-yaml-prompt.md)

**Comment by nakamori-naoya** [comment]
## プロンプト更新内容

プロンプトを以下のように更新しました：

### 変更点

1. **コアドメインの識別セクションを削除**
   - 競争優位性などの記述は不要とのフィードバックを反映

2. **時間的制約の詳細化**
   ```yaml
   temporal_constraints:
     - constraint: "時間に関する制約"
       type: "期限|順序|タイミング|周期|時間帯"
       details:
         deadline: "具体的な期限（例：3営業日以内）"
         sequence: "順序関係（例：AはBの前に完了必須）"
         timing: "特定のタイミング（例：月末、決算期）"
         frequency: "頻度（例：日次、月次、随時）"
         time_window: "実行可能時間帯（例：営業時間内のみ）"
       business_reason: "なぜこのタイミングが重要か"
       consequences: "守られなかった場合の影響"
       exceptions:
         - case: "例外となるケース"
           handling: "例外時の扱い"
   ```

3. **新規追加した構造化要素**
   - **暗黙知・経験則**: 言語化されていない業務知識
   - **判断基準とトレードオフ**: 意思決定の基準と優先順位
   - **外部制約**: 法規制・業界標準・契約
   - **リスクと対処**: リスクの検知と軽減策
   - **依存関係**: 他システムやプロセスへの依存

### プロンプトの評価

**このプロンプトは生成AIが業務知識を正しく言語化するのに十分機能すると評価します。**

#### 良い点
- 網羅性が高く、業務知識の重要な側面をカバー
- 「なぜ」を重視した構造で、AIが文脈を理解しやすい
- 具体例の記載を要求し、曖昧さを排除
- 例外処理を考慮し、現実の業務の複雑さに対応

#### 改善可能な点
- 項目が多いため、必須項目と任意項目の区別があると良い
- 記載の粒度やレベル感の目安があると使いやすい

## YAML構造の完全版

プロンプトには以下の要素が含まれています：

1. 対象業務の概要（目的・成功基準を含む）
2. 業務概念と制約（不変条件・ライフサイクル）
3. ビジネスルール（検証・計算・判定・制限）
4. 業務イベント（トリガー・事前/事後条件）
5. 業務フロー（ステップごとの条件と検証）
6. 用語定義（ユビキタス言語）
7. 時間的制約（期限・順序・タイミング・周期・時間帯）
8. 暗黙知・経験則
9. 判断基準とトレードオフ
10. 外部制約（法規制・業界標準）
11. リスクと対処
12. 依存関係

これにより、業務知識を体系的かつ実践的に構造化できます。
