### ISSUE TITLE
業務知識YAML準拠コード評価プロンプト

### ISSUE THREAD

**Issue by nakamori-naoya** [nakamori-naoya/engineering-guidelines#21]
# 業務知識YAML準拠コード評価プロンプト

業務知識YAMLで定義された内容に対して、実装コードとテストコードが正しく準拠しているかを徹底的に評価します。

## 評価対象

1. **業務知識YAML**: 構造化された業務知識の定義
2. **実装コード**: プロダクションコード
3. **テストコード**: 単体テスト、統合テスト

## 評価手順

以下の手順で体系的に評価を実施してください：

### 1. 業務知識YAMLの読み込みと理解
- 全ての制約条件、不変条件、ビジネスルールを抽出
- 状態遷移とライフサイクルを把握
- 時間的制約、外部制約を確認

#### 2.1 制約条件の実装評価
```yaml
evaluation_criteria:
  constraints:
    - yaml_constraint: "YAMLで定義された制約"
      implementation_status: "実装済み|未実装|部分的"
      code_location: "実装箇所（ファイル名:行番号）"
      implementation_quality:
        correctness: "正しく実装されているか"
        completeness: "全てのケースをカバーしているか"
        error_handling: "違反時の処理は適切か"
      missing_elements:
        - "不足している実装内容"
      improvement_suggestions:
        - "改善提案"
```

#### 2.2 ビジネスルールの実装評価
```yaml
business_rules_evaluation:
  - rule_name: "ルール名"
    yaml_definition: "YAMLでの定義"
    implementation:
      found: true/false
      location: "実装箇所"
      correct_logic: "ロジックは正しいか"
      handles_exceptions: "例外処理は実装されているか"
      missing_scenarios:
        - "未実装のシナリオ"
```

#### 2.3 状態遷移の実装評価
```yaml
state_transitions_evaluation:
  - transition: "状態A → 状態B"
    trigger_event: "トリガーイベント"
    implementation:
      state_management: "状態管理の実装方法"
      transition_guards: "遷移条件のガード実装"
      atomicity: "原子性は保証されているか"
      rollback_capability: "ロールバック可能か"
```

#### 2.4 時間的制約の実装評価
```yaml
temporal_constraints_evaluation:
  - constraint: "時間制約"
    implementation:
      deadline_enforcement: "期限の強制実装"
      sequence_validation: "順序の検証実装"
      timing_checks: "タイミングチェック実装"
      timeout_handling: "タイムアウト処理"
```

#### 3.1 制約条件のテスト評価
```yaml
constraint_test_evaluation:
  - constraint: "制約条件"
    test_coverage:
      positive_cases: "正常系テストの有無"
      negative_cases: "異常系テストの有無"
      boundary_cases: "境界値テストの有無"
      edge_cases: "エッジケーステストの有無"
    missing_tests:
      - "不足しているテストケース"
```

#### 3.2 ビジネスルールのテスト評価
```yaml
business_rule_test_evaluation:
  - rule: "ビジネスルール"
    test_scenarios:
      main_flow: "メインフローのテスト"
      exception_flows: "例外フローのテスト"
      calculation_accuracy: "計算精度のテスト"
    test_quality:
      assertions: "アサーションは適切か"
      test_data: "テストデータは網羅的か"
      isolation: "テストは独立しているか"
```

#### 3.3 状態遷移のテスト評価
```yaml
state_transition_test_evaluation:
  - transition: "状態遷移"
    test_coverage:
      valid_transitions: "有効な遷移のテスト"
      invalid_transitions: "無効な遷移のテスト"
      concurrent_transitions: "並行遷移のテスト"
      state_persistence: "状態永続化のテスト"
```

### 4. 総合評価レポート

```yaml
comprehensive_evaluation_report:
  summary:
    compliance_score: "準拠度スコア（0-100）"
    coverage_percentage: "カバレッジ率"
    critical_issues: "重大な問題の数"
    
  detailed_findings:
    fully_implemented:
      - feature: "完全実装された機能"
        quality: "実装品質"
    
    partially_implemented:
      - feature: "部分実装の機能"
        missing_parts: "不足部分"
        completion_percentage: "完成度"
    
    not_implemented:
      - feature: "未実装の機能"
        priority: "実装優先度"
        effort_estimate: "実装工数見積"
    
  risk_assessment:
    high_risk:
      - issue: "高リスクの問題"
        impact: "影響範囲"
        mitigation: "軽減策"
    
    medium_risk:
      - issue: "中リスクの問題"
        
    low_risk:
      - issue: "低リスクの問題"
  
  recommendations:
    immediate_actions:
      - action: "即座に対応すべきアクション"
        reason: "理由"
        implementation_guide: "実装ガイド"
    
    short_term:
      - action: "短期的な改善項目"
        
    long_term:
      - action: "長期的な改善項目"
```

### 5. 具体的な改善提案

```yaml
improvement_proposals:
  missing_implementations:
    - feature: "不足機能"
      code_example: |
        # 実装例
        class BusinessRule:
            def validate(self, data):
                # 具体的な実装コード
                pass
      
      test_example: |
        # テスト例
        def test_business_rule():
            # 具体的なテストコード
            assert rule.validate(data) == expected
  
  refactoring_suggestions:
    - current_issue: "現在の問題"
      proposed_solution: "提案する解決策"
      benefits: "改善によるメリット"
  
  test_improvements:
    - test_type: "テストの種類"
      missing_scenarios: "不足シナリオ"
      test_code_template: "テストコードのテンプレート"
```

## 評価時の重要ポイント

1. **業務言語の一致性**
   - コード内の変数名、関数名が業務用語と一致しているか
   - コメントが業務知識を反映しているか

2. **防御的プログラミング**
   - 全ての制約がガードされているか
   - 想定外の入力に対する処理があるか

3. **トレーサビリティ**
   - YAMLの各要素がコードのどこに対応するか明確か
   - 変更時の影響範囲が追跡可能か

4. **保守性**
   - ビジネスルールが変更しやすい構造か
   - テストが理解しやすく保守しやすいか

## 使用方法

1. 業務知識YAML、実装コード、テストコードを入力
2. 上記の評価基準に従って体系的に分析
3. 具体的な改善提案を含む評価レポートを生成

## 出力例

```yaml
evaluation_result:
  summary:
    compliance_score: 75
    message: "主要な制約は実装されているが、時間的制約とエッジケースの対応が不足"
  
  critical_findings:
    - "期限管理の実装が完全に欠落"
    - "並行処理時の状態整合性が保証されていない"
  
  immediate_actions:
    - description: "期限チェック機能の実装"
      priority: "HIGH"
      example_code: |
        def check_deadline(order_date, current_date):
            deadline = order_date + timedelta(days=3)
            if current_date > deadline:
                raise DeadlineExceededError()
```

---

このプロンプトを使用して、業務知識の実装品質を徹底的に評価し、具体的な改善につなげてください。
