### ISSUE TITLE
エンティティ分類の手引き

### ISSUE THREAD

**Issue by nakamori-naoya** [nakamori-naoya/engineering-guidelines#9]
# 🤖 生成AIへの重要な指示

このドキュメントはエンティティ分類（リソース vs イベント）の判断手引きである。
YAMLブロック内の構造化データを最優先で読み込み、判断フローとチェックリストに従って正確な分類を行うこと。

## 🤖 AI向け構造化データ

```yaml
document_type: "entity_classification_guide"
purpose: "リソースとイベントの判断手引き"
version: "1.0"
related_issue: "#8"
priority: "high"
usage_context: "データベース設計・イミュータブルデータモデル"

# 判断フロー（必須手順）
decision_flow:
  step1:
    question: "その概念に「いつ」という情報が本質的に含まれているか？"
    yes: "イベントの可能性大"
    no: "リソースの可能性大"
  
  step2:  
    question: "「〜する」を付けて自然か？"
    yes: "イベント確定"
    no: "リソース確定"
    
  step3:
    question: "一度発生したら変更されない事実か？"
    yes: "イベント"
    no: "リソース"

# 判断基準
criteria:
  event_indicators:
    - "時間情報が本質的"
    - "動詞化が自然"
    - "不変の事実"
    - "何が起きたかの記録"
    - "生成されて終わり"
    
  resource_indicators:
    - "時間情報は付随的"
    - "動詞化が不自然"
    - "変更可能な状態"
    - "現在の状態管理"
    - "生成後も変化"

# よくある間違い（回避必須）
common_mistakes:
  - type: "name_confusion"
    description: "名前（マスタ、履歴、ログ）に惑わされる"
    
  - type: "implementation_bias" 
    description: "テーブル構造や処理方式に引きずられる"
    
  - type: "specification_limitation"
    description: "現在の仕様要件に縛られる"

# 境界が曖昧なケース
ambiguous_cases:
  status_entities:
    example: "承認済み注文"
    correct_approach: "注文（イベント） + 注文承認（イベント）に分解"
    
  history_logs:
    example: "アクセスログ"
    correct_approach: "アクセスというイベントの記録として扱う"
    
  5w1h_exceptions:
    when_as_resource: ["営業日カレンダー", "会計期間", "キャンペーン期間"]
    who_as_event: ["来店者（来店イベントの一部）", "応募者（応募イベントの一部）"]

# 必須チェックリスト
mandatory_checklist:
  - "5W1Hのどれに該当するか確認"
  - "「〜する」テストを実施"
  - "日時属性の有無を確認"
  - "ライフサイクルを考慮"
  - "隠れたイベントの可能性を検討"
  - "3大要素（単一性・同一性・カテゴリ）を定義"

# 実例による判断例
examples:
  order:
    classification: "イベント"
    reasoning: "いつ注文したかが本質的、「注文する」は自然、一度注文した事実は不変"
    
  customer:
    classification: "リソース"  
    reasoning: "いつという情報は本質的でない、「顧客する」は不自然、顧客情報は変更される"
    
  inventory:
    classification: "リソース"
    reasoning: "いつという情報は本質的でない、「在庫する」は不自然、在庫数は変動"
```

---

関連: #8

# エンティティ分類の手引き

### 1. リソースかイベントか判断できない
「これはリソースですか？イベントですか？」と迷った時の判断フロー

#### 判断フロー
```
1. その概念に「いつ」という情報が本質的に含まれているか？
   YES → イベントの可能性大
   NO  → リソースの可能性大

2. 「〜する」を付けて自然か？
   YES → イベント確定
   NO  → リソース確定

3. 一度発生したら変更されない事実か？
   YES → イベント
   NO  → リソース
```

#### 具体例での判断

**例1: 「注文」**
- いつ注文したかが本質的 → YES
- 「注文する」は自然 → YES
- 一度注文した事実は変わらない → YES
- **結論: イベント**

**例2: 「顧客」**
- いつという情報は本質的でない → NO
- 「顧客する」は不自然 → NO
- 顧客情報は変更される → NO
- **結論: リソース**

**例3: 「在庫」**
- いつという情報は本質的でない → NO
- 「在庫する」は不自然 → NO
- 在庫数は変動する → NO
- **結論: リソース**

#### ステータス系の扱い
**迷いやすい例: 「承認済み注文」**

間違った解釈：
- 承認済みという状態を持つから、これは1つのエンティティ

正しい解釈：
- 「注文」（イベント）
- 「注文承認」（イベント）
- 2つの独立したイベント

#### 履歴・ログ系の扱い
**迷いやすい例: 「アクセスログ」**

考え方：
- ログ = 何かが起きた記録
- 本質は「アクセス」というイベント
- **結論: イベント**

#### Whenがリソースになるケース
- 「営業日カレンダー」
- 「会計期間」
- 「キャンペーン期間」

これらは期間や日付を管理する**リソース**

#### Whoがイベントになるケース
- 「来店者」（来店というイベントの一部）
- 「応募者」（応募というイベントの一部）

文脈により判断が必要

### データのライフサイクルで考える
1. **生成されて終わり** → イベント
2. **生成後も変化する** → リソース

### ビジネス価値で考える
1. **何が起きたかの記録** → イベント
2. **現在の状態の管理** → リソース

### 更新の観点で考える
1. **更新されたら過去の情報が失われて困る** → イベント
2. **最新の状態だけあればよい** → リソース（ただし履歴が必要なら別途検討）

### 1. 名前に惑わされる
- 「マスタ」という名前 → 必ずしもリソースではない
- 「履歴」という名前 → 必ずしもイベントではない
- 「ログ」という名前 → ほぼイベントだが文脈確認

### 2. 実装に引きずられる
- 「テーブルが1つだから1エンティティ」→ 間違い
- 「更新処理があるからリソース」→ 間違い（隠れたイベントかも）

### 3. 現在の仕様に縛られる
- 「今は変更しないから」→ 本質的に変更可能かで判断
- 「今は履歴不要だから」→ ビジネス的に履歴が意味を持つかで判断

## 🔍 チェックリスト

エンティティ分類で迷ったら：

- [ ] 5W1Hのどれに該当するか確認した
- [ ] 「〜する」テストを実施した
- [ ] 日時属性の有無を確認した
- [ ] ライフサイクルを考慮した
- [ ] 隠れたイベントの可能性を検討した
- [ ] 3大要素（単一性・同一性・カテゴリ）を定義した
